###Question: Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first terms will be:
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

a = 1
b = 1
max = 4000000
sum = 0

while a < max:
    if( a % 2 == 0):
        sum += a
    a, b = b, a + b
    

print(sum)





